(part "WSHP28183L000FEA"
    (packageRef "WSHP28183L000FEA")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Mouser_Part_Number" "71-WSHP28183L000FEA")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Dale/WSHP28183L000FEA?qs=u4fy%2FsgLU9PGDWS9IKHQYw%3D%3D")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "WSHP28183L000FEA")
    (property "Description" "Current Sense Resistors - SMD 10W .003ohms 1%")
    (property "Datasheet_Link" "https://www.vishay.com/doc?30347")
    (property "symbolName1" "WSHP28183L000FEA")
)
