(part "LM4132AMF-1_8_NOPB"
    (packageRef "SOT95P280X145-5N")
    (interface
        (port "1" (symbPinId 1) (portName "N/C") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "EN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VIN") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VREF") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "926-LM4132AMF18NOPB")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/LM4132AMF-18-NOPB?qs=QbsRYf82W3HnSfMLOwla5A%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "LM4132AMF-1.8/NOPB")
    (property "Description" "0.05% 20ppm/C Drift Precision Series Voltage Reference with Shutdown Enable")
    (property "Datasheet_Link" "http://www.ti.com/lit/ds/symlink/lm4132.pdf")
    (property "symbolName1" "LM4132AMF-1_8_NOPB")
)
